name: Deploy Backend

on:
  workflow_dispatch:

jobs:
  deploy_backend:
    name: Upload to Lambda
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        role-to-assume: arn:aws:iam::441747338187:role/RoleForGithubActionsUploadToLambda
        role-duration-seconds: 1200
        aws-region: us-east-1

    - name: Upload to Lambdas
      run: |
        aws --version
        ls -la